# Configuration file for Google App Engine deployment
runtime: python39  # Specifies Python 3.9 runtime environment
entrypoint: gunicorn -b :$PORT main:app  # Runs Gunicorn with Flask app on specified port

handlers:
  # Serve static files from the 'static' directory
  - url: /static
    static_dir: static
  # Route all other requests to the Flask app
  - url: /.*
    script: auto